// export const NBA_TEAM_CITIES = [
//   "atl",
//   "bos",
//   "bkn",
//   "cha",
//   "chi",
//   "cle",
//   "dal",
//   "den",
//   "det",
//   "gs",
//   "hou",
//   "ind",
//   "lac",
//   "lal",
//   "mem",
//   "mia",
//   "mil",
//   "min",
//   "no",
//   "ny",
//   "okc",
//   "orl",
//   "phi",
//   "phx",
//   "por",
//   "sac",
//   "sa",
//   "tor",
//   "utah",
//   "wsh",
// ];

export const NBA_TEAMS_STANDINGS = [
  { city: "atl", conference: "East" },
  { city: "bos", conference: "East" },
  { city: "bkn", conference: "East" },
  { city: "cha", conference: "East" },
  { city: "chi", conference: "East" },
  { city: "cle", conference: "East" },
  { city: "dal", conference: "West" },
  { city: "den", conference: "West" },
  { city: "det", conference: "East" },
  { city: "gs", conference: "West" },
  { city: "hou", conference: "West" },
  { city: "ind", conference: "East" },
  { city: "lac", conference: "West" },
  { city: "lal", conference: "West" },
  { city: "mem", conference: "West" },
  { city: "mia", conference: "East" },
  { city: "mil", conference: "East" },
  { city: "min", conference: "West" },
  { city: "no", conference: "West" },
  { city: "ny", conference: "East" },
  { city: "okc", conference: "West" },
  { city: "orl", conference: "East" },
  { city: "phi", conference: "East" },
  { city: "phx", conference: "West" },
  { city: "por", conference: "West" },
  { city: "sac", conference: "West" },
  { city: "sa", conference: "West" },
  { city: "tor", conference: "East" },
  { city: "utah", conference: "West" },
  { city: "wsh", conference: "East" },
];
